export const MATCHES = [
    {'Ben': ['Johanna',]},
    {'Caitlin': ['Jordan',]},
    {'Daragh': ['Gillian', 'Jonathan',]},
    {'Gillian': ['Jonathan', 'Daragh',]},
    {'Jess': ['Rich',]},
    {'Johanna': ['Ben']},
    {'Jonathan': ['Gillian', 'Daragh',]},
    {'Katherine': ['Ali',]},
    {'Liam': ['Poppy',]},
    {'Marco': ['Dan',]},
    {'Poppy': ['Liam',]},
    {'Rich': ['Jess',]},
    {'Dan': ['Marco',]},
    {'Ali': ['Katherine',]},
    {'Jordan': ['Caitlin']},
];

export const IDS = {
    'Ben': "U1354RD7F",
    'Caitlin': "UUADM1015",
    'Daragh': "U018UH9110S",
    'Gillian':"U019VH60FMY",
    'Jess': "U0122TX7KUM",
    'Johanna':"U012V2U68JK",
    'Jonathan':"U0166A6AYQ2",
    'Katherine':"U027F9P3AHK",
    'Liam':"U01SBMN9TDM",
    'Marco':"U01KV9N0VFE",
    'Poppy':"U01L6MRS3B5",
    'Rich':"UF7VB5ASW",
    'Dan':"UN8ER3T1Q",
    'Ali':"U01UHCS9ZCP",
    'Jordan':"U12Q7RXRV",
};
